# Generated by Django 4.0.4 on 2023-03-02 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ktogra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ktogra.team'),
            preserve_default=False,
        ),
    ]
