# Generated by Django 4.0.4 on 2023-03-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktogra', '0003_todo_delete_match_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('home', models.CharField(max_length=128)),
                ('away', models.CharField(max_length=128)),
                ('league', models.IntegerField()),
            ],
        ),
    ]
