# Generated by Django 4.0.4 on 2023-03-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktogra', '0005_match_gameweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='kolejka',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
