# Generated by Django 4.0.4 on 2023-03-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktogra', '0006_match_kolejka'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AlterModelTable(
            name='match',
            table='matches',
        ),
    ]
