# Generated by Django 4.0.4 on 2023-03-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktogra', '0007_delete_todo_alter_match_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
