# Generated by Django 4.0.4 on 2023-03-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktogra', '0010_alter_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='match',
            name='home',
            field=models.CharField(max_length=128),
        ),
    ]
