# Generated by Django 4.0.4 on 2023-03-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktogra', '0014_alter_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
