# Generated by Django 4.0.4 on 2023-03-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktogra', '0015_alter_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
