# Generated by Django 4.0.4 on 2023-03-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktogra', '0016_alter_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='description',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
