# Generated by Django 4.0.4 on 2023-03-03 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktogra', '0017_match_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='description',
        ),
    ]
