# Generated by Django 4.0.4 on 2023-03-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktogra', '0018_remove_match_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='description',
            field=models.CharField(default='match', max_length=128),
        ),
    ]
